version: "3.8"

services:
  admin:
    container_name: kuba_admin_container
    image: node
    user: ${CURRENT_UID}
    volumes:
      - ./:/kuba
    command: bash -c "cd kuba && yarn && cd admin && yarn start"
    ports:
      - "3001:3001"
  api:
    container_name: kuba_api_container
    image: node
    user: ${CURRENT_UID}
    volumes:
      - ./:/kuba
    command: bash -c "cd kuba && yarn && cd api && npx prisma migrate dev --name init && yarn start:dev"
    ports:
      - "3000:3000"
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
